apiVersion: v1
kind: Service   # Тип ресурсу — Service, використовується для доступу до Pod
metadata:
metadata:
  name: olegk-app  # Ім'я сервісу
  namespace: olegk-app  # Простір імен, у якому створюється цей сервіс
spec:
  selector:
    app: olegk-app  # Визначає, до яких Pod підключатися
  ports:
  - protocol: TCP  # Протокол зв'язку (TCP — стандартний для HTTP)
    port: 80   # Порт, на якому сервіс всередині кластера
    targetPort: 5000   # Порт контейнера, до якого спрямовується трафік
  type: ClusterIP    # Тип сервісу (ClusterIP — доступ тільки всередині кластера)