name: Build and Push Docker Image

on:
  workflow_dispatch:  # Запуск вручну

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: olegk-app  # Використовуємо змінну із "Variables" репозиторію
      IMAGE_TAG: v1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} app/

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
