name: Build and Push Docker Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: kalinichenkoit/olegk-app  # Використовуємо змінну із "Variables" репозиторію
      IMAGE_TAG: v2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: |
          cd app
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Update Kubernetes manifests (deployment.yaml)
        run: |
          ls -lh kube-deploy
          sed -i 's|image: .*|image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|' kube-deploy/deploy-app.yml

      - name: Commit updated Kubernetes manifests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add kube-deploy/deploy-app.yml
          git commit -m "Update Docker image tag to latest"
          git push